############# default cfg #############


#server
server:
  contextPath: /

git:
  uri: http://gitlab.yit.com/javayuanjian/prd.git
  user: javayuanjian
  pwd: cliveyuan

gitprd:
  cfg:
    root_path_name: gitPRD
