############# default cfg #############


#server
server:
  contextPath: /

git:
  uri: xxx
  user: xxx
  pwd: xxx

gitprd:
  cfg:
    # gitPRD workspace path in /Users/{user}/
    root_path_name: gitPRD
  server_uri: http://prd2.yit.com
